M48
; DRILL file KiCad 10.0.2 date 2026-05-16T20:23:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-16T20:23:02-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.810
%
G90
G05
T1
X131.0Y-72.5
X135.5Y-135.5
X166.5Y-135.5
X171.0Y-72.5
T2
X156.0Y-71.0
X163.5Y-71.0
M30
